// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: another_search_packet.proto

package another_search_packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Another_Search_Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShowresultId      string                           `protobuf:"bytes,1,opt,name=showresultId,proto3" json:"showresultId,omitempty"`
	LeaveDate         string                           `protobuf:"bytes,2,opt,name=leaveDate,proto3" json:"leaveDate,omitempty"`
	HomeDate          string                           `protobuf:"bytes,3,opt,name=homeDate,proto3" json:"homeDate,omitempty"`
	Adults            uint32                           `protobuf:"varint,4,opt,name=adults,proto3" json:"adults,omitempty"`
	ChildrenAges      string                           `protobuf:"bytes,5,opt,name=childrenAges,proto3" json:"childrenAges,omitempty"`
	YouthAges         string                           `protobuf:"bytes,6,opt,name=youthAges,proto3" json:"youthAges,omitempty"`
	TicketType        string                           `protobuf:"bytes,7,opt,name=ticketType,proto3" json:"ticketType,omitempty"`
	SearchTimestamp   string                           `protobuf:"bytes,8,opt,name=searchTimestamp,proto3" json:"searchTimestamp,omitempty"`
	To                string                           `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`
	From              string                           `protobuf:"bytes,10,opt,name=from,proto3" json:"from,omitempty"`
	TripType          string                           `protobuf:"bytes,11,opt,name=tripType,proto3" json:"tripType,omitempty"`
	Domain            string                           `protobuf:"bytes,12,opt,name=domain,proto3" json:"domain,omitempty"`
	IsBaggageIncluded bool                             `protobuf:"varint,13,opt,name=isBaggageIncluded,proto3" json:"isBaggageIncluded,omitempty"`
	Legs              []*Another_Search_Packet_Legs    `protobuf:"bytes,14,rep,name=legs,proto3" json:"legs,omitempty"`
	Device            string                           `protobuf:"bytes,15,opt,name=device,proto3" json:"device,omitempty"`
	Flights           []*Another_Search_Packet_Flights `protobuf:"bytes,16,rep,name=flights,proto3" json:"flights,omitempty"`
}

func (x *Another_Search_Packet) Reset() {
	*x = Another_Search_Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_another_search_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Another_Search_Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Another_Search_Packet) ProtoMessage() {}

func (x *Another_Search_Packet) ProtoReflect() protoreflect.Message {
	mi := &file_another_search_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Another_Search_Packet.ProtoReflect.Descriptor instead.
func (*Another_Search_Packet) Descriptor() ([]byte, []int) {
	return file_another_search_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Another_Search_Packet) GetShowresultId() string {
	if x != nil {
		return x.ShowresultId
	}
	return ""
}

func (x *Another_Search_Packet) GetLeaveDate() string {
	if x != nil {
		return x.LeaveDate
	}
	return ""
}

func (x *Another_Search_Packet) GetHomeDate() string {
	if x != nil {
		return x.HomeDate
	}
	return ""
}

func (x *Another_Search_Packet) GetAdults() uint32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *Another_Search_Packet) GetChildrenAges() string {
	if x != nil {
		return x.ChildrenAges
	}
	return ""
}

func (x *Another_Search_Packet) GetYouthAges() string {
	if x != nil {
		return x.YouthAges
	}
	return ""
}

func (x *Another_Search_Packet) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

func (x *Another_Search_Packet) GetSearchTimestamp() string {
	if x != nil {
		return x.SearchTimestamp
	}
	return ""
}

func (x *Another_Search_Packet) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Another_Search_Packet) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Another_Search_Packet) GetTripType() string {
	if x != nil {
		return x.TripType
	}
	return ""
}

func (x *Another_Search_Packet) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Another_Search_Packet) GetIsBaggageIncluded() bool {
	if x != nil {
		return x.IsBaggageIncluded
	}
	return false
}

func (x *Another_Search_Packet) GetLegs() []*Another_Search_Packet_Legs {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *Another_Search_Packet) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Another_Search_Packet) GetFlights() []*Another_Search_Packet_Flights {
	if x != nil {
		return x.Flights
	}
	return nil
}

type Another_Search_Packet_Legs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Date string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Another_Search_Packet_Legs) Reset() {
	*x = Another_Search_Packet_Legs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_another_search_packet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Another_Search_Packet_Legs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Another_Search_Packet_Legs) ProtoMessage() {}

func (x *Another_Search_Packet_Legs) ProtoReflect() protoreflect.Message {
	mi := &file_another_search_packet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Another_Search_Packet_Legs.ProtoReflect.Descriptor instead.
func (*Another_Search_Packet_Legs) Descriptor() ([]byte, []int) {
	return file_another_search_packet_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Another_Search_Packet_Legs) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Another_Search_Packet_Legs) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Another_Search_Packet_Legs) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Another_Search_Packet_Agents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Price uint32 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Another_Search_Packet_Agents) Reset() {
	*x = Another_Search_Packet_Agents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_another_search_packet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Another_Search_Packet_Agents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Another_Search_Packet_Agents) ProtoMessage() {}

func (x *Another_Search_Packet_Agents) ProtoReflect() protoreflect.Message {
	mi := &file_another_search_packet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Another_Search_Packet_Agents.ProtoReflect.Descriptor instead.
func (*Another_Search_Packet_Agents) Descriptor() ([]byte, []int) {
	return file_another_search_packet_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Another_Search_Packet_Agents) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Another_Search_Packet_Agents) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Another_Search_Packet_Segments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArrivalAirport   string `protobuf:"bytes,1,opt,name=arrivalAirport,proto3" json:"arrivalAirport,omitempty"`
	ArrivalDate      string `protobuf:"bytes,2,opt,name=arrivalDate,proto3" json:"arrivalDate,omitempty"`
	DepartureAirport string `protobuf:"bytes,3,opt,name=departureAirport,proto3" json:"departureAirport,omitempty"`
	DepartureDate    string `protobuf:"bytes,4,opt,name=departureDate,proto3" json:"departureDate,omitempty"`
	Traveltime       uint32 `protobuf:"varint,5,opt,name=traveltime,proto3" json:"traveltime,omitempty"`
	Flight           string `protobuf:"bytes,6,opt,name=flight,proto3" json:"flight,omitempty"`
}

func (x *Another_Search_Packet_Segments) Reset() {
	*x = Another_Search_Packet_Segments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_another_search_packet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Another_Search_Packet_Segments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Another_Search_Packet_Segments) ProtoMessage() {}

func (x *Another_Search_Packet_Segments) ProtoReflect() protoreflect.Message {
	mi := &file_another_search_packet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Another_Search_Packet_Segments.ProtoReflect.Descriptor instead.
func (*Another_Search_Packet_Segments) Descriptor() ([]byte, []int) {
	return file_another_search_packet_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Another_Search_Packet_Segments) GetArrivalAirport() string {
	if x != nil {
		return x.ArrivalAirport
	}
	return ""
}

func (x *Another_Search_Packet_Segments) GetArrivalDate() string {
	if x != nil {
		return x.ArrivalDate
	}
	return ""
}

func (x *Another_Search_Packet_Segments) GetDepartureAirport() string {
	if x != nil {
		return x.DepartureAirport
	}
	return ""
}

func (x *Another_Search_Packet_Segments) GetDepartureDate() string {
	if x != nil {
		return x.DepartureDate
	}
	return ""
}

func (x *Another_Search_Packet_Segments) GetTraveltime() uint32 {
	if x != nil {
		return x.Traveltime
	}
	return 0
}

func (x *Another_Search_Packet_Segments) GetFlight() string {
	if x != nil {
		return x.Flight
	}
	return ""
}

type Another_Search_Packet_Trips struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Segments []*Another_Search_Packet_Segments `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *Another_Search_Packet_Trips) Reset() {
	*x = Another_Search_Packet_Trips{}
	if protoimpl.UnsafeEnabled {
		mi := &file_another_search_packet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Another_Search_Packet_Trips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Another_Search_Packet_Trips) ProtoMessage() {}

func (x *Another_Search_Packet_Trips) ProtoReflect() protoreflect.Message {
	mi := &file_another_search_packet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Another_Search_Packet_Trips.ProtoReflect.Descriptor instead.
func (*Another_Search_Packet_Trips) Descriptor() ([]byte, []int) {
	return file_another_search_packet_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Another_Search_Packet_Trips) GetSegments() []*Another_Search_Packet_Segments {
	if x != nil {
		return x.Segments
	}
	return nil
}

type Another_Search_Packet_Flights struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents           []*Another_Search_Packet_Agents `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Trips            []*Another_Search_Packet_Trips  `protobuf:"bytes,2,rep,name=trips,proto3" json:"trips,omitempty"`
	SearchIdentifier string                          `protobuf:"bytes,3,opt,name=searchIdentifier,proto3" json:"searchIdentifier,omitempty"`
}

func (x *Another_Search_Packet_Flights) Reset() {
	*x = Another_Search_Packet_Flights{}
	if protoimpl.UnsafeEnabled {
		mi := &file_another_search_packet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Another_Search_Packet_Flights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Another_Search_Packet_Flights) ProtoMessage() {}

func (x *Another_Search_Packet_Flights) ProtoReflect() protoreflect.Message {
	mi := &file_another_search_packet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Another_Search_Packet_Flights.ProtoReflect.Descriptor instead.
func (*Another_Search_Packet_Flights) Descriptor() ([]byte, []int) {
	return file_another_search_packet_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Another_Search_Packet_Flights) GetAgents() []*Another_Search_Packet_Agents {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *Another_Search_Packet_Flights) GetTrips() []*Another_Search_Packet_Trips {
	if x != nil {
		return x.Trips
	}
	return nil
}

func (x *Another_Search_Packet_Flights) GetSearchIdentifier() string {
	if x != nil {
		return x.SearchIdentifier
	}
	return ""
}

var File_another_search_packet_proto protoreflect.FileDescriptor

var file_another_search_packet_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61,
	0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x22, 0xce, 0x09, 0x0a, 0x15, 0x41, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x5f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x64, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x64,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x41, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x41, 0x67, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x79, 0x6f, 0x75, 0x74,
	0x68, 0x41, 0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x79, 0x6f, 0x75,
	0x74, 0x68, 0x41, 0x67, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x69, 0x73, 0x42, 0x61,
	0x67, 0x67, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x11, 0x69, 0x73, 0x42, 0x61, 0x67, 0x67, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x04, 0x6c, 0x65, 0x67, 0x73, 0x18, 0x0e,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x41, 0x6e, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x5f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x4c, 0x65, 0x67, 0x73, 0x52, 0x04, 0x6c, 0x65, 0x67, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x41,
	0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x07, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x1a, 0x3e, 0x0a, 0x04, 0x4c, 0x65, 0x67, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x32, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x1a, 0xde, 0x01, 0x0a, 0x08, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61,
	0x6c, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x2a, 0x0a, 0x10, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x41, 0x69, 0x72,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x75, 0x72, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x0d,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x5a, 0x0a, 0x05, 0x54, 0x72,
	0x69, 0x70, 0x73, 0x12, 0x51, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x41, 0x6e,
	0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x08, 0x73, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0xcc, 0x01, 0x0a, 0x07, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x12, 0x4b, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x33, 0x2e, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x41, 0x6e, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x5f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x48, 0x0a, 0x05, 0x74, 0x72, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32,
	0x2e, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x41, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x54, 0x72, 0x69,
	0x70, 0x73, 0x52, 0x05, 0x74, 0x72, 0x69, 0x70, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_another_search_packet_proto_rawDescOnce sync.Once
	file_another_search_packet_proto_rawDescData = file_another_search_packet_proto_rawDesc
)

func file_another_search_packet_proto_rawDescGZIP() []byte {
	file_another_search_packet_proto_rawDescOnce.Do(func() {
		file_another_search_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_another_search_packet_proto_rawDescData)
	})
	return file_another_search_packet_proto_rawDescData
}

var file_another_search_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_another_search_packet_proto_goTypes = []interface{}{
	(*Another_Search_Packet)(nil),          // 0: another_search_packet.Another_Search_Packet
	(*Another_Search_Packet_Legs)(nil),     // 1: another_search_packet.Another_Search_Packet.Legs
	(*Another_Search_Packet_Agents)(nil),   // 2: another_search_packet.Another_Search_Packet.Agents
	(*Another_Search_Packet_Segments)(nil), // 3: another_search_packet.Another_Search_Packet.Segments
	(*Another_Search_Packet_Trips)(nil),    // 4: another_search_packet.Another_Search_Packet.Trips
	(*Another_Search_Packet_Flights)(nil),  // 5: another_search_packet.Another_Search_Packet.Flights
}
var file_another_search_packet_proto_depIdxs = []int32{
	1, // 0: another_search_packet.Another_Search_Packet.legs:type_name -> another_search_packet.Another_Search_Packet.Legs
	5, // 1: another_search_packet.Another_Search_Packet.flights:type_name -> another_search_packet.Another_Search_Packet.Flights
	3, // 2: another_search_packet.Another_Search_Packet.Trips.segments:type_name -> another_search_packet.Another_Search_Packet.Segments
	2, // 3: another_search_packet.Another_Search_Packet.Flights.agents:type_name -> another_search_packet.Another_Search_Packet.Agents
	4, // 4: another_search_packet.Another_Search_Packet.Flights.trips:type_name -> another_search_packet.Another_Search_Packet.Trips
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_another_search_packet_proto_init() }
func file_another_search_packet_proto_init() {
	if File_another_search_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_another_search_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Another_Search_Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_another_search_packet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Another_Search_Packet_Legs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_another_search_packet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Another_Search_Packet_Agents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_another_search_packet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Another_Search_Packet_Segments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_another_search_packet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Another_Search_Packet_Trips); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_another_search_packet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Another_Search_Packet_Flights); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_another_search_packet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_another_search_packet_proto_goTypes,
		DependencyIndexes: file_another_search_packet_proto_depIdxs,
		MessageInfos:      file_another_search_packet_proto_msgTypes,
	}.Build()
	File_another_search_packet_proto = out.File
	file_another_search_packet_proto_rawDesc = nil
	file_another_search_packet_proto_goTypes = nil
	file_another_search_packet_proto_depIdxs = nil
}
