// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: click_packet.proto

package click_packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Click_Packet struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ShowresultId           string                 `protobuf:"bytes,1,opt,name=showresultId,proto3" json:"showresultId,omitempty"`
	LeaveDate              string                 `protobuf:"bytes,2,opt,name=leaveDate,proto3" json:"leaveDate,omitempty"`
	HomeDate               string                 `protobuf:"bytes,3,opt,name=homeDate,proto3" json:"homeDate,omitempty"`
	Adults                 uint32                 `protobuf:"varint,4,opt,name=adults,proto3" json:"adults,omitempty"`
	ChildrenAges           string                 `protobuf:"bytes,5,opt,name=childrenAges,proto3" json:"childrenAges,omitempty"`
	YouthAges              string                 `protobuf:"bytes,6,opt,name=youthAges,proto3" json:"youthAges,omitempty"`
	TicketType             string                 `protobuf:"bytes,7,opt,name=ticketType,proto3" json:"ticketType,omitempty"`
	SearchTimestamp        string                 `protobuf:"bytes,8,opt,name=searchTimestamp,proto3" json:"searchTimestamp,omitempty"`
	To                     string                 `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`
	From                   string                 `protobuf:"bytes,10,opt,name=from,proto3" json:"from,omitempty"`
	TripType               string                 `protobuf:"bytes,11,opt,name=tripType,proto3" json:"tripType,omitempty"`
	Domain                 string                 `protobuf:"bytes,12,opt,name=domain,proto3" json:"domain,omitempty"`
	IsBaggageIncluded      bool                   `protobuf:"varint,13,opt,name=isBaggageIncluded,proto3" json:"isBaggageIncluded,omitempty"`
	IsCabinBaggageIncluded bool                   `protobuf:"varint,18,opt,name=isCabinBaggageIncluded,proto3" json:"isCabinBaggageIncluded,omitempty"`
	Legs                   []*Click_Packet_Legs   `protobuf:"bytes,14,rep,name=legs,proto3" json:"legs,omitempty"`
	Device                 string                 `protobuf:"bytes,15,opt,name=device,proto3" json:"device,omitempty"`
	Clicked                *Click_Packet_Clicked  `protobuf:"bytes,16,opt,name=clicked,proto3" json:"clicked,omitempty"`
	SearchIdentifier       string                 `protobuf:"bytes,17,opt,name=searchIdentifier,proto3" json:"searchIdentifier,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Click_Packet) Reset() {
	*x = Click_Packet{}
	mi := &file_click_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Click_Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click_Packet) ProtoMessage() {}

func (x *Click_Packet) ProtoReflect() protoreflect.Message {
	mi := &file_click_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click_Packet.ProtoReflect.Descriptor instead.
func (*Click_Packet) Descriptor() ([]byte, []int) {
	return file_click_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Click_Packet) GetShowresultId() string {
	if x != nil {
		return x.ShowresultId
	}
	return ""
}

func (x *Click_Packet) GetLeaveDate() string {
	if x != nil {
		return x.LeaveDate
	}
	return ""
}

func (x *Click_Packet) GetHomeDate() string {
	if x != nil {
		return x.HomeDate
	}
	return ""
}

func (x *Click_Packet) GetAdults() uint32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *Click_Packet) GetChildrenAges() string {
	if x != nil {
		return x.ChildrenAges
	}
	return ""
}

func (x *Click_Packet) GetYouthAges() string {
	if x != nil {
		return x.YouthAges
	}
	return ""
}

func (x *Click_Packet) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

func (x *Click_Packet) GetSearchTimestamp() string {
	if x != nil {
		return x.SearchTimestamp
	}
	return ""
}

func (x *Click_Packet) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Click_Packet) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Click_Packet) GetTripType() string {
	if x != nil {
		return x.TripType
	}
	return ""
}

func (x *Click_Packet) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Click_Packet) GetIsBaggageIncluded() bool {
	if x != nil {
		return x.IsBaggageIncluded
	}
	return false
}

func (x *Click_Packet) GetIsCabinBaggageIncluded() bool {
	if x != nil {
		return x.IsCabinBaggageIncluded
	}
	return false
}

func (x *Click_Packet) GetLegs() []*Click_Packet_Legs {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *Click_Packet) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Click_Packet) GetClicked() *Click_Packet_Clicked {
	if x != nil {
		return x.Clicked
	}
	return nil
}

func (x *Click_Packet) GetSearchIdentifier() string {
	if x != nil {
		return x.SearchIdentifier
	}
	return ""
}

type Click_Packet_Legs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Click_Packet_Legs) Reset() {
	*x = Click_Packet_Legs{}
	mi := &file_click_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Click_Packet_Legs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click_Packet_Legs) ProtoMessage() {}

func (x *Click_Packet_Legs) ProtoReflect() protoreflect.Message {
	mi := &file_click_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click_Packet_Legs.ProtoReflect.Descriptor instead.
func (*Click_Packet_Legs) Descriptor() ([]byte, []int) {
	return file_click_packet_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Click_Packet_Legs) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Click_Packet_Legs) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Click_Packet_Legs) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Click_Packet_Clicked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentCode     string                 `protobuf:"bytes,1,opt,name=agentCode,proto3" json:"agentCode,omitempty"`
	Price         uint32                 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Click_Packet_Clicked) Reset() {
	*x = Click_Packet_Clicked{}
	mi := &file_click_packet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Click_Packet_Clicked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click_Packet_Clicked) ProtoMessage() {}

func (x *Click_Packet_Clicked) ProtoReflect() protoreflect.Message {
	mi := &file_click_packet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click_Packet_Clicked.ProtoReflect.Descriptor instead.
func (*Click_Packet_Clicked) Descriptor() ([]byte, []int) {
	return file_click_packet_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Click_Packet_Clicked) GetAgentCode() string {
	if x != nil {
		return x.AgentCode
	}
	return ""
}

func (x *Click_Packet_Clicked) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_click_packet_proto protoreflect.FileDescriptor

const file_click_packet_proto_rawDesc = "" +
	"\n" +
	"\x12click_packet.proto\x12\fclick_packet\"\x84\x06\n" +
	"\fClick_Packet\x12\"\n" +
	"\fshowresultId\x18\x01 \x01(\tR\fshowresultId\x12\x1c\n" +
	"\tleaveDate\x18\x02 \x01(\tR\tleaveDate\x12\x1a\n" +
	"\bhomeDate\x18\x03 \x01(\tR\bhomeDate\x12\x16\n" +
	"\x06adults\x18\x04 \x01(\rR\x06adults\x12\"\n" +
	"\fchildrenAges\x18\x05 \x01(\tR\fchildrenAges\x12\x1c\n" +
	"\tyouthAges\x18\x06 \x01(\tR\tyouthAges\x12\x1e\n" +
	"\n" +
	"ticketType\x18\a \x01(\tR\n" +
	"ticketType\x12(\n" +
	"\x0fsearchTimestamp\x18\b \x01(\tR\x0fsearchTimestamp\x12\x0e\n" +
	"\x02to\x18\t \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\n" +
	" \x01(\tR\x04from\x12\x1a\n" +
	"\btripType\x18\v \x01(\tR\btripType\x12\x16\n" +
	"\x06domain\x18\f \x01(\tR\x06domain\x12,\n" +
	"\x11isBaggageIncluded\x18\r \x01(\bR\x11isBaggageIncluded\x126\n" +
	"\x16isCabinBaggageIncluded\x18\x12 \x01(\bR\x16isCabinBaggageIncluded\x123\n" +
	"\x04legs\x18\x0e \x03(\v2\x1f.click_packet.Click_Packet.LegsR\x04legs\x12\x16\n" +
	"\x06device\x18\x0f \x01(\tR\x06device\x12<\n" +
	"\aclicked\x18\x10 \x01(\v2\".click_packet.Click_Packet.ClickedR\aclicked\x12*\n" +
	"\x10searchIdentifier\x18\x11 \x01(\tR\x10searchIdentifier\x1a>\n" +
	"\x04Legs\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x1a=\n" +
	"\aClicked\x12\x1c\n" +
	"\tagentCode\x18\x01 \x01(\tR\tagentCode\x12\x14\n" +
	"\x05price\x18\x02 \x01(\rR\x05priceB\x10Z\x0e./click_packetb\x06proto3"

var (
	file_click_packet_proto_rawDescOnce sync.Once
	file_click_packet_proto_rawDescData []byte
)

func file_click_packet_proto_rawDescGZIP() []byte {
	file_click_packet_proto_rawDescOnce.Do(func() {
		file_click_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_click_packet_proto_rawDesc), len(file_click_packet_proto_rawDesc)))
	})
	return file_click_packet_proto_rawDescData
}

var file_click_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_click_packet_proto_goTypes = []any{
	(*Click_Packet)(nil),         // 0: click_packet.Click_Packet
	(*Click_Packet_Legs)(nil),    // 1: click_packet.Click_Packet.Legs
	(*Click_Packet_Clicked)(nil), // 2: click_packet.Click_Packet.Clicked
}
var file_click_packet_proto_depIdxs = []int32{
	1, // 0: click_packet.Click_Packet.legs:type_name -> click_packet.Click_Packet.Legs
	2, // 1: click_packet.Click_Packet.clicked:type_name -> click_packet.Click_Packet.Clicked
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_click_packet_proto_init() }
func file_click_packet_proto_init() {
	if File_click_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_click_packet_proto_rawDesc), len(file_click_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_click_packet_proto_goTypes,
		DependencyIndexes: file_click_packet_proto_depIdxs,
		MessageInfos:      file_click_packet_proto_msgTypes,
	}.Build()
	File_click_packet_proto = out.File
	file_click_packet_proto_goTypes = nil
	file_click_packet_proto_depIdxs = nil
}
