// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: search_packet.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Search_Packet struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	ShowresultId           string                   `protobuf:"bytes,1,opt,name=showresultId,proto3" json:"showresultId,omitempty"`
	LeaveDate              string                   `protobuf:"bytes,2,opt,name=leaveDate,proto3" json:"leaveDate,omitempty"`
	HomeDate               string                   `protobuf:"bytes,3,opt,name=homeDate,proto3" json:"homeDate,omitempty"`
	Adults                 uint32                   `protobuf:"varint,4,opt,name=adults,proto3" json:"adults,omitempty"`
	ChildrenAges           string                   `protobuf:"bytes,5,opt,name=childrenAges,proto3" json:"childrenAges,omitempty"`
	YouthAges              string                   `protobuf:"bytes,6,opt,name=youthAges,proto3" json:"youthAges,omitempty"`
	TicketType             string                   `protobuf:"bytes,7,opt,name=ticketType,proto3" json:"ticketType,omitempty"`
	SearchTimestamp        string                   `protobuf:"bytes,8,opt,name=searchTimestamp,proto3" json:"searchTimestamp,omitempty"`
	To                     string                   `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`
	From                   string                   `protobuf:"bytes,10,opt,name=from,proto3" json:"from,omitempty"`
	TripType               string                   `protobuf:"bytes,11,opt,name=tripType,proto3" json:"tripType,omitempty"`
	Domain                 string                   `protobuf:"bytes,12,opt,name=domain,proto3" json:"domain,omitempty"`
	IsBaggageIncluded      bool                     `protobuf:"varint,13,opt,name=isBaggageIncluded,proto3" json:"isBaggageIncluded,omitempty"`
	IsCabinBaggageIncluded bool                     `protobuf:"varint,17,opt,name=isCabinBaggageIncluded,proto3" json:"isCabinBaggageIncluded,omitempty"`
	Legs                   []*Search_Packet_Legs    `protobuf:"bytes,14,rep,name=legs,proto3" json:"legs,omitempty"`
	Device                 string                   `protobuf:"bytes,15,opt,name=device,proto3" json:"device,omitempty"`
	Flights                []*Search_Packet_Flights `protobuf:"bytes,16,rep,name=flights,proto3" json:"flights,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Search_Packet) Reset() {
	*x = Search_Packet{}
	mi := &file_search_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Packet) ProtoMessage() {}

func (x *Search_Packet) ProtoReflect() protoreflect.Message {
	mi := &file_search_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Packet.ProtoReflect.Descriptor instead.
func (*Search_Packet) Descriptor() ([]byte, []int) {
	return file_search_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Search_Packet) GetShowresultId() string {
	if x != nil {
		return x.ShowresultId
	}
	return ""
}

func (x *Search_Packet) GetLeaveDate() string {
	if x != nil {
		return x.LeaveDate
	}
	return ""
}

func (x *Search_Packet) GetHomeDate() string {
	if x != nil {
		return x.HomeDate
	}
	return ""
}

func (x *Search_Packet) GetAdults() uint32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *Search_Packet) GetChildrenAges() string {
	if x != nil {
		return x.ChildrenAges
	}
	return ""
}

func (x *Search_Packet) GetYouthAges() string {
	if x != nil {
		return x.YouthAges
	}
	return ""
}

func (x *Search_Packet) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

func (x *Search_Packet) GetSearchTimestamp() string {
	if x != nil {
		return x.SearchTimestamp
	}
	return ""
}

func (x *Search_Packet) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Search_Packet) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Search_Packet) GetTripType() string {
	if x != nil {
		return x.TripType
	}
	return ""
}

func (x *Search_Packet) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Search_Packet) GetIsBaggageIncluded() bool {
	if x != nil {
		return x.IsBaggageIncluded
	}
	return false
}

func (x *Search_Packet) GetIsCabinBaggageIncluded() bool {
	if x != nil {
		return x.IsCabinBaggageIncluded
	}
	return false
}

func (x *Search_Packet) GetLegs() []*Search_Packet_Legs {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *Search_Packet) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Search_Packet) GetFlights() []*Search_Packet_Flights {
	if x != nil {
		return x.Flights
	}
	return nil
}

type Search_Packet_Legs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search_Packet_Legs) Reset() {
	*x = Search_Packet_Legs{}
	mi := &file_search_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_Packet_Legs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Packet_Legs) ProtoMessage() {}

func (x *Search_Packet_Legs) ProtoReflect() protoreflect.Message {
	mi := &file_search_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Packet_Legs.ProtoReflect.Descriptor instead.
func (*Search_Packet_Legs) Descriptor() ([]byte, []int) {
	return file_search_packet_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Search_Packet_Legs) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Search_Packet_Legs) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Search_Packet_Legs) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Search_Packet_Agents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Price         uint32                 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search_Packet_Agents) Reset() {
	*x = Search_Packet_Agents{}
	mi := &file_search_packet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_Packet_Agents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Packet_Agents) ProtoMessage() {}

func (x *Search_Packet_Agents) ProtoReflect() protoreflect.Message {
	mi := &file_search_packet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Packet_Agents.ProtoReflect.Descriptor instead.
func (*Search_Packet_Agents) Descriptor() ([]byte, []int) {
	return file_search_packet_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Search_Packet_Agents) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Search_Packet_Agents) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Search_Packet_Segments struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ArrivalAirport   string                 `protobuf:"bytes,1,opt,name=arrivalAirport,proto3" json:"arrivalAirport,omitempty"`
	ArrivalDate      string                 `protobuf:"bytes,2,opt,name=arrivalDate,proto3" json:"arrivalDate,omitempty"`
	DepartureAirport string                 `protobuf:"bytes,3,opt,name=departureAirport,proto3" json:"departureAirport,omitempty"`
	DepartureDate    string                 `protobuf:"bytes,4,opt,name=departureDate,proto3" json:"departureDate,omitempty"`
	Traveltime       uint32                 `protobuf:"varint,5,opt,name=traveltime,proto3" json:"traveltime,omitempty"`
	Flight           string                 `protobuf:"bytes,6,opt,name=flight,proto3" json:"flight,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Search_Packet_Segments) Reset() {
	*x = Search_Packet_Segments{}
	mi := &file_search_packet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_Packet_Segments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Packet_Segments) ProtoMessage() {}

func (x *Search_Packet_Segments) ProtoReflect() protoreflect.Message {
	mi := &file_search_packet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Packet_Segments.ProtoReflect.Descriptor instead.
func (*Search_Packet_Segments) Descriptor() ([]byte, []int) {
	return file_search_packet_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Search_Packet_Segments) GetArrivalAirport() string {
	if x != nil {
		return x.ArrivalAirport
	}
	return ""
}

func (x *Search_Packet_Segments) GetArrivalDate() string {
	if x != nil {
		return x.ArrivalDate
	}
	return ""
}

func (x *Search_Packet_Segments) GetDepartureAirport() string {
	if x != nil {
		return x.DepartureAirport
	}
	return ""
}

func (x *Search_Packet_Segments) GetDepartureDate() string {
	if x != nil {
		return x.DepartureDate
	}
	return ""
}

func (x *Search_Packet_Segments) GetTraveltime() uint32 {
	if x != nil {
		return x.Traveltime
	}
	return 0
}

func (x *Search_Packet_Segments) GetFlight() string {
	if x != nil {
		return x.Flight
	}
	return ""
}

type Search_Packet_Trips struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Segments      []*Search_Packet_Segments `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search_Packet_Trips) Reset() {
	*x = Search_Packet_Trips{}
	mi := &file_search_packet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_Packet_Trips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Packet_Trips) ProtoMessage() {}

func (x *Search_Packet_Trips) ProtoReflect() protoreflect.Message {
	mi := &file_search_packet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Packet_Trips.ProtoReflect.Descriptor instead.
func (*Search_Packet_Trips) Descriptor() ([]byte, []int) {
	return file_search_packet_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Search_Packet_Trips) GetSegments() []*Search_Packet_Segments {
	if x != nil {
		return x.Segments
	}
	return nil
}

type Search_Packet_Flights struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Agents           []*Search_Packet_Agents `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Trips            []*Search_Packet_Trips  `protobuf:"bytes,2,rep,name=trips,proto3" json:"trips,omitempty"`
	SearchIdentifier string                  `protobuf:"bytes,3,opt,name=searchIdentifier,proto3" json:"searchIdentifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Search_Packet_Flights) Reset() {
	*x = Search_Packet_Flights{}
	mi := &file_search_packet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_Packet_Flights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Packet_Flights) ProtoMessage() {}

func (x *Search_Packet_Flights) ProtoReflect() protoreflect.Message {
	mi := &file_search_packet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Packet_Flights.ProtoReflect.Descriptor instead.
func (*Search_Packet_Flights) Descriptor() ([]byte, []int) {
	return file_search_packet_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Search_Packet_Flights) GetAgents() []*Search_Packet_Agents {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *Search_Packet_Flights) GetTrips() []*Search_Packet_Trips {
	if x != nil {
		return x.Trips
	}
	return nil
}

func (x *Search_Packet_Flights) GetSearchIdentifier() string {
	if x != nil {
		return x.SearchIdentifier
	}
	return ""
}

var File_search_packet_proto protoreflect.FileDescriptor

const file_search_packet_proto_rawDesc = "" +
	"\n" +
	"\x13search_packet.proto\x12\rsearch_packet\"\xae\t\n" +
	"\rSearch_Packet\x12\"\n" +
	"\fshowresultId\x18\x01 \x01(\tR\fshowresultId\x12\x1c\n" +
	"\tleaveDate\x18\x02 \x01(\tR\tleaveDate\x12\x1a\n" +
	"\bhomeDate\x18\x03 \x01(\tR\bhomeDate\x12\x16\n" +
	"\x06adults\x18\x04 \x01(\rR\x06adults\x12\"\n" +
	"\fchildrenAges\x18\x05 \x01(\tR\fchildrenAges\x12\x1c\n" +
	"\tyouthAges\x18\x06 \x01(\tR\tyouthAges\x12\x1e\n" +
	"\n" +
	"ticketType\x18\a \x01(\tR\n" +
	"ticketType\x12(\n" +
	"\x0fsearchTimestamp\x18\b \x01(\tR\x0fsearchTimestamp\x12\x0e\n" +
	"\x02to\x18\t \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\n" +
	" \x01(\tR\x04from\x12\x1a\n" +
	"\btripType\x18\v \x01(\tR\btripType\x12\x16\n" +
	"\x06domain\x18\f \x01(\tR\x06domain\x12,\n" +
	"\x11isBaggageIncluded\x18\r \x01(\bR\x11isBaggageIncluded\x126\n" +
	"\x16isCabinBaggageIncluded\x18\x11 \x01(\bR\x16isCabinBaggageIncluded\x125\n" +
	"\x04legs\x18\x0e \x03(\v2!.search_packet.Search_Packet.LegsR\x04legs\x12\x16\n" +
	"\x06device\x18\x0f \x01(\tR\x06device\x12>\n" +
	"\aflights\x18\x10 \x03(\v2$.search_packet.Search_Packet.FlightsR\aflights\x1a>\n" +
	"\x04Legs\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x1a2\n" +
	"\x06Agents\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05price\x18\x02 \x01(\rR\x05price\x1a\xde\x01\n" +
	"\bSegments\x12&\n" +
	"\x0earrivalAirport\x18\x01 \x01(\tR\x0earrivalAirport\x12 \n" +
	"\varrivalDate\x18\x02 \x01(\tR\varrivalDate\x12*\n" +
	"\x10departureAirport\x18\x03 \x01(\tR\x10departureAirport\x12$\n" +
	"\rdepartureDate\x18\x04 \x01(\tR\rdepartureDate\x12\x1e\n" +
	"\n" +
	"traveltime\x18\x05 \x01(\rR\n" +
	"traveltime\x12\x16\n" +
	"\x06flight\x18\x06 \x01(\tR\x06flight\x1aJ\n" +
	"\x05Trips\x12A\n" +
	"\bsegments\x18\x01 \x03(\v2%.search_packet.Search_Packet.SegmentsR\bsegments\x1a\xac\x01\n" +
	"\aFlights\x12;\n" +
	"\x06agents\x18\x01 \x03(\v2#.search_packet.Search_Packet.AgentsR\x06agents\x128\n" +
	"\x05trips\x18\x02 \x03(\v2\".search_packet.Search_Packet.TripsR\x05trips\x12*\n" +
	"\x10searchIdentifier\x18\x03 \x01(\tR\x10searchIdentifierB\x04Z\x02./b\x06proto3"

var (
	file_search_packet_proto_rawDescOnce sync.Once
	file_search_packet_proto_rawDescData []byte
)

func file_search_packet_proto_rawDescGZIP() []byte {
	file_search_packet_proto_rawDescOnce.Do(func() {
		file_search_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_packet_proto_rawDesc), len(file_search_packet_proto_rawDesc)))
	})
	return file_search_packet_proto_rawDescData
}

var file_search_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_search_packet_proto_goTypes = []any{
	(*Search_Packet)(nil),          // 0: search_packet.Search_Packet
	(*Search_Packet_Legs)(nil),     // 1: search_packet.Search_Packet.Legs
	(*Search_Packet_Agents)(nil),   // 2: search_packet.Search_Packet.Agents
	(*Search_Packet_Segments)(nil), // 3: search_packet.Search_Packet.Segments
	(*Search_Packet_Trips)(nil),    // 4: search_packet.Search_Packet.Trips
	(*Search_Packet_Flights)(nil),  // 5: search_packet.Search_Packet.Flights
}
var file_search_packet_proto_depIdxs = []int32{
	1, // 0: search_packet.Search_Packet.legs:type_name -> search_packet.Search_Packet.Legs
	5, // 1: search_packet.Search_Packet.flights:type_name -> search_packet.Search_Packet.Flights
	3, // 2: search_packet.Search_Packet.Trips.segments:type_name -> search_packet.Search_Packet.Segments
	2, // 3: search_packet.Search_Packet.Flights.agents:type_name -> search_packet.Search_Packet.Agents
	4, // 4: search_packet.Search_Packet.Flights.trips:type_name -> search_packet.Search_Packet.Trips
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_search_packet_proto_init() }
func file_search_packet_proto_init() {
	if File_search_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_packet_proto_rawDesc), len(file_search_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_search_packet_proto_goTypes,
		DependencyIndexes: file_search_packet_proto_depIdxs,
		MessageInfos:      file_search_packet_proto_msgTypes,
	}.Build()
	File_search_packet_proto = out.File
	file_search_packet_proto_goTypes = nil
	file_search_packet_proto_depIdxs = nil
}
