// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: another_click_packet.proto

package another_click_packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Another_Click_Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShowresultId      string                        `protobuf:"bytes,1,opt,name=showresultId,proto3" json:"showresultId,omitempty"`
	LeaveDate         string                        `protobuf:"bytes,2,opt,name=leaveDate,proto3" json:"leaveDate,omitempty"`
	HomeDate          string                        `protobuf:"bytes,3,opt,name=homeDate,proto3" json:"homeDate,omitempty"`
	Adults            uint32                        `protobuf:"varint,4,opt,name=adults,proto3" json:"adults,omitempty"`
	ChildrenAges      string                        `protobuf:"bytes,5,opt,name=childrenAges,proto3" json:"childrenAges,omitempty"`
	YouthAges         string                        `protobuf:"bytes,6,opt,name=youthAges,proto3" json:"youthAges,omitempty"`
	TicketType        string                        `protobuf:"bytes,7,opt,name=ticketType,proto3" json:"ticketType,omitempty"`
	SearchTimestamp   string                        `protobuf:"bytes,8,opt,name=searchTimestamp,proto3" json:"searchTimestamp,omitempty"`
	To                string                        `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`
	From              string                        `protobuf:"bytes,10,opt,name=from,proto3" json:"from,omitempty"`
	TripType          string                        `protobuf:"bytes,11,opt,name=tripType,proto3" json:"tripType,omitempty"`
	Domain            string                        `protobuf:"bytes,12,opt,name=domain,proto3" json:"domain,omitempty"`
	IsBaggageIncluded bool                          `protobuf:"varint,13,opt,name=isBaggageIncluded,proto3" json:"isBaggageIncluded,omitempty"`
	Legs              []*Another_Click_Packet_Legs  `protobuf:"bytes,14,rep,name=legs,proto3" json:"legs,omitempty"`
	Device            string                        `protobuf:"bytes,15,opt,name=device,proto3" json:"device,omitempty"`
	Clicked           *Another_Click_Packet_Clicked `protobuf:"bytes,16,opt,name=clicked,proto3" json:"clicked,omitempty"`
	SearchIdentifier  string                        `protobuf:"bytes,17,opt,name=searchIdentifier,proto3" json:"searchIdentifier,omitempty"`
}

func (x *Another_Click_Packet) Reset() {
	*x = Another_Click_Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_another_click_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Another_Click_Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Another_Click_Packet) ProtoMessage() {}

func (x *Another_Click_Packet) ProtoReflect() protoreflect.Message {
	mi := &file_another_click_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Another_Click_Packet.ProtoReflect.Descriptor instead.
func (*Another_Click_Packet) Descriptor() ([]byte, []int) {
	return file_another_click_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Another_Click_Packet) GetShowresultId() string {
	if x != nil {
		return x.ShowresultId
	}
	return ""
}

func (x *Another_Click_Packet) GetLeaveDate() string {
	if x != nil {
		return x.LeaveDate
	}
	return ""
}

func (x *Another_Click_Packet) GetHomeDate() string {
	if x != nil {
		return x.HomeDate
	}
	return ""
}

func (x *Another_Click_Packet) GetAdults() uint32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *Another_Click_Packet) GetChildrenAges() string {
	if x != nil {
		return x.ChildrenAges
	}
	return ""
}

func (x *Another_Click_Packet) GetYouthAges() string {
	if x != nil {
		return x.YouthAges
	}
	return ""
}

func (x *Another_Click_Packet) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

func (x *Another_Click_Packet) GetSearchTimestamp() string {
	if x != nil {
		return x.SearchTimestamp
	}
	return ""
}

func (x *Another_Click_Packet) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Another_Click_Packet) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Another_Click_Packet) GetTripType() string {
	if x != nil {
		return x.TripType
	}
	return ""
}

func (x *Another_Click_Packet) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Another_Click_Packet) GetIsBaggageIncluded() bool {
	if x != nil {
		return x.IsBaggageIncluded
	}
	return false
}

func (x *Another_Click_Packet) GetLegs() []*Another_Click_Packet_Legs {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *Another_Click_Packet) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Another_Click_Packet) GetClicked() *Another_Click_Packet_Clicked {
	if x != nil {
		return x.Clicked
	}
	return nil
}

func (x *Another_Click_Packet) GetSearchIdentifier() string {
	if x != nil {
		return x.SearchIdentifier
	}
	return ""
}

type Another_Click_Packet_Legs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Date string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Another_Click_Packet_Legs) Reset() {
	*x = Another_Click_Packet_Legs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_another_click_packet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Another_Click_Packet_Legs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Another_Click_Packet_Legs) ProtoMessage() {}

func (x *Another_Click_Packet_Legs) ProtoReflect() protoreflect.Message {
	mi := &file_another_click_packet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Another_Click_Packet_Legs.ProtoReflect.Descriptor instead.
func (*Another_Click_Packet_Legs) Descriptor() ([]byte, []int) {
	return file_another_click_packet_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Another_Click_Packet_Legs) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Another_Click_Packet_Legs) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Another_Click_Packet_Legs) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Another_Click_Packet_Clicked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentCode string `protobuf:"bytes,1,opt,name=agentCode,proto3" json:"agentCode,omitempty"`
	Price     uint32 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Another_Click_Packet_Clicked) Reset() {
	*x = Another_Click_Packet_Clicked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_another_click_packet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Another_Click_Packet_Clicked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Another_Click_Packet_Clicked) ProtoMessage() {}

func (x *Another_Click_Packet_Clicked) ProtoReflect() protoreflect.Message {
	mi := &file_another_click_packet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Another_Click_Packet_Clicked.ProtoReflect.Descriptor instead.
func (*Another_Click_Packet_Clicked) Descriptor() ([]byte, []int) {
	return file_another_click_packet_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Another_Click_Packet_Clicked) GetAgentCode() string {
	if x != nil {
		return x.AgentCode
	}
	return ""
}

func (x *Another_Click_Packet_Clicked) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_another_click_packet_proto protoreflect.FileDescriptor

var file_another_click_packet_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x5f,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61, 0x6e,
	0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x5f, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x22, 0xf4, 0x05, 0x0a, 0x14, 0x41, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x43,
	0x6c, 0x69, 0x63, 0x6b, 0x5f, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73,
	0x68, 0x6f, 0x77, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x6f, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x6f, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x64, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x64, 0x75, 0x6c, 0x74,
	0x73, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x41, 0x67, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65,
	0x6e, 0x41, 0x67, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x79, 0x6f, 0x75, 0x74, 0x68, 0x41, 0x67,
	0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x79, 0x6f, 0x75, 0x74, 0x68, 0x41,
	0x67, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x69, 0x73, 0x42, 0x61, 0x67, 0x67, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x11, 0x69, 0x73, 0x42, 0x61, 0x67, 0x67, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x63, 0x6c, 0x75,
	0x64, 0x65, 0x64, 0x12, 0x43, 0x0a, 0x04, 0x6c, 0x65, 0x67, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69, 0x63,
	0x6b, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x41, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x5f, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x5f, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x65,
	0x67, 0x73, 0x52, 0x04, 0x6c, 0x65, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4c, 0x0a, 0x07, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x32, 0x2e, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69, 0x63,
	0x6b, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x41, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x5f, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x5f, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x43, 0x6c,
	0x69, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x07, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x2a,
	0x0a, 0x10, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x1a, 0x3e, 0x0a, 0x04, 0x4c, 0x65,
	0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x3d, 0x0a, 0x07, 0x43, 0x6c,
	0x69, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_another_click_packet_proto_rawDescOnce sync.Once
	file_another_click_packet_proto_rawDescData = file_another_click_packet_proto_rawDesc
)

func file_another_click_packet_proto_rawDescGZIP() []byte {
	file_another_click_packet_proto_rawDescOnce.Do(func() {
		file_another_click_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_another_click_packet_proto_rawDescData)
	})
	return file_another_click_packet_proto_rawDescData
}

var file_another_click_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_another_click_packet_proto_goTypes = []interface{}{
	(*Another_Click_Packet)(nil),         // 0: another_click_packet.Another_Click_Packet
	(*Another_Click_Packet_Legs)(nil),    // 1: another_click_packet.Another_Click_Packet.Legs
	(*Another_Click_Packet_Clicked)(nil), // 2: another_click_packet.Another_Click_Packet.Clicked
}
var file_another_click_packet_proto_depIdxs = []int32{
	1, // 0: another_click_packet.Another_Click_Packet.legs:type_name -> another_click_packet.Another_Click_Packet.Legs
	2, // 1: another_click_packet.Another_Click_Packet.clicked:type_name -> another_click_packet.Another_Click_Packet.Clicked
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_another_click_packet_proto_init() }
func file_another_click_packet_proto_init() {
	if File_another_click_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_another_click_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Another_Click_Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_another_click_packet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Another_Click_Packet_Legs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_another_click_packet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Another_Click_Packet_Clicked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_another_click_packet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_another_click_packet_proto_goTypes,
		DependencyIndexes: file_another_click_packet_proto_depIdxs,
		MessageInfos:      file_another_click_packet_proto_msgTypes,
	}.Build()
	File_another_click_packet_proto = out.File
	file_another_click_packet_proto_rawDesc = nil
	file_another_click_packet_proto_goTypes = nil
	file_another_click_packet_proto_depIdxs = nil
}
